
services:
  db:
    image: postgres:15-alpine
    container_name: coleta_escolar_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coleta_escolar
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapeia a pasta database/init.sql para que o PostgreSQL rode esse script ao subir a primeira vez
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
