// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ColetaDbContext))]
    [Migration("20260905175134_AddUsuariosTable")]
    partial class AddUsuariosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Aluno", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_aluno")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CpfAluno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_aluno");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("DescricaoNecessidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_necessidade");

                    b.Property<Guid>("IdFamilia")
                        .HasColumnType("uuid")
                        .HasColumnName("id_familia");

                    b.Property<bool>("NecessidadeEducacionalEspecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("necessidade_educacional_especial");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_aluno");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sexo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdAluno");

                    b.HasIndex("CpfAluno")
                        .IsUnique();

                    b.HasIndex("IdFamilia");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("Entities.Models.AlunoResponsavel", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uuid")
                        .HasColumnName("id_aluno");

                    b.Property<Guid>("IdResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("id_responsavel");

                    b.Property<string>("ParentescoResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parentesco_responsavel");

                    b.HasKey("IdAluno", "IdResponsavel");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("aluno_responsavel", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Familia", b =>
                {
                    b.Property<Guid>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_familia")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("BeneficioSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("beneficio_social");

                    b.Property<string>("Comunidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comunidade");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endereco");

                    b.Property<bool>("PossuiInternetCasa")
                        .HasColumnType("boolean")
                        .HasColumnName("possui_internet_casa");

                    b.Property<int>("QtdMoradores")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_moradores");

                    b.Property<bool>("RecebeBeneficioSocial")
                        .HasColumnType("boolean")
                        .HasColumnName("recebe_beneficio_social");

                    b.Property<decimal>("RendaFamiliarMensal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("renda_familiar_mensal");

                    b.Property<string>("TipoAcessoInternet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_acesso_internet");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdFamilia");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Matricula", b =>
                {
                    b.Property<Guid>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_matricula")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("AnoSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ano_serie");

                    b.Property<decimal>("FrequenciaEscolarPct")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("frequencia_escolar_pct");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uuid")
                        .HasColumnName("id_aluno");

                    b.Property<string>("MeioTransporteEscola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("meio_transporte_escola");

                    b.Property<int>("TempoDeslocamentoMin")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_deslocamento_min");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("turno");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdAluno");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("Entities.Models.RegistroColeta", b =>
                {
                    b.Property<Guid>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_registro");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_coleta");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uuid")
                        .HasColumnName("id_aluno");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("StatusSincronizacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("SINCRONIZADO")
                        .HasColumnName("status_sincronizacao");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdAluno");

                    b.ToTable("registros_coleta", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Responsavel", b =>
                {
                    b.Property<Guid>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_responsavel")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CpfResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_responsavel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_responsavel");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_responsavel");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_responsavel");

                    b.HasKey("IdResponsavel");

                    b.HasIndex("CpfResponsavel")
                        .IsUnique();

                    b.ToTable("responsaveis", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entities.Models.Aluno", b =>
                {
                    b.HasOne("Entities.Models.Familia", "Familia")
                        .WithMany("Alunos")
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_familia");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Entities.Models.AlunoResponsavel", b =>
                {
                    b.HasOne("Entities.Models.Aluno", "Aluno")
                        .WithMany("Responsaveis")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ar_aluno");

                    b.HasOne("Entities.Models.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ar_responsavel");

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Entities.Models.Matricula", b =>
                {
                    b.HasOne("Entities.Models.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matricula_aluno");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Entities.Models.RegistroColeta", b =>
                {
                    b.HasOne("Entities.Models.Aluno", "Aluno")
                        .WithMany("RegistrosColeta")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registro_aluno");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Entities.Models.Aluno", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("RegistrosColeta");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("Entities.Models.Familia", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Entities.Models.Responsavel", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
